BUILD_ALL += $(OUT_DIR)/sparkfun_detector_power_bins

$(OUT_DIR)/sparkfun_detector_power_bins : \
					$(OUT_OBJ_DIR)/example_service_power_bins.o \
					libacconeer.a \
					libacconeer_sensor.a \
					libcustomer.a \
					libacc_service.a \
					$(OUT_OBJ_DIR)/acc_board_rpi_sparkfun.o
	@echo "    Linking $(notdir $@)"
	$(SUPPRESS)mkdir -p $(OUT_DIR)
	$(SUPPRESS)$(LINK.o) -Wl,--start-group $^ -Wl,--end-group $(LOADLIBES) $(LDLIBS) -o $@
